### ISSUE TITLE
Make Server and credential configuration possible in IDE

### ISSUE THREAD

**Issue by lorriborri** [mercedes-benz/sechub-plugin-eclipse#36]
## Situation
The user is not able to configure SecHub server and its credentials via the IDE

## Wanted 
It should be possible for users to define the credentials and the URL for the SecHub server securely in the IDE.

## Solution
- Via the settings dialog the user should be able to store the configurations.
- save credentials via preferences secure storage
- New SecHub View/ Dialog
- The Server view shows server URL, username and alive status

**Comment by de-jcup** [comment]
With last commit it looks like this:

![image](https://github.com/user-attachments/assets/4f75b183-1c74-43a3-b70f-75b7a7990890)

![image](https://github.com/user-attachments/assets/209a9e9f-fc8e-4548-bce5-77e572726665)

![image](https://github.com/user-attachments/assets/ac52a352-b8f7-426d-885f-d4cd1eeb35c7)
